### ISSUE TITLE
Phantom Path Error on Windows

### ISSUE THREAD

**Issue by jagreehal** [wallabyjs/wallaby-webpack-es7#4]
Somewhere down the line the call to phantomjs doesn't handle paths on Windows

phantom stderr: 'C:\Users\Jag' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ArtemGovorov** [comment]
Trying to reproduce it on Windows 8, no luck yet. Does it happen on the project without any modifications during the first wallaby run or I have to make some changes to reproduce it?

Anyway, could you please start wallaby, and once the error occurs open "Wallaby Console" tab in your IDE. `Ctrl + F` in the console and search for `http://localhost:`. You should be able to find the URL of wallaby sandbox, the port number is dynamic, the URL looks like: http://localhost:xxxxx/wallaby_sandbox0.html. Without stopping wallaby, open the URL in Chrome, open Chrome Dev Tools console and paste some details from there please.

**Comment by ArtemGovorov** [comment]
After doing some research on the error, it seems it's a known issue with phantomjs and paths with spaces: 
http://stackoverflow.com/questions/29846359/phantom-stderr-error-when-running-local-prerender

Could you please try to download phantomjs from https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip, extract it to a folder without spaces, and add `env` setting with `runner` property set to the path of the phantomjs.exe?

``` JavaScript
...
files: [...],
tests: [...],
compilers: {...},
env: {
  runner: 'C:\\no_spaces_path\\phantomjs.exe'
}
...
```
